# Generated by Django 4.2.30 on 2026-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_emission_factor_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnormalizedemissionrecord',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
    ]
